/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.controller;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.Library;
import org.json.JSONArray;
import org.json.JSONObject;
import sun.security.jca.GetInstance;

/**
 *
 * @ onlick.author Welcome
 */
public class view1 extends javax.swing.JFrame {

    /**
     * Creates new form view1
     */
    
    private static view1 myIns;
    
    public static view1 getIns() {
        if (myIns == null) {
            myIns = new view1();
        }
        return myIns;
    }
    
    public view1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        listLib = new javax.swing.JList();
        loadLib = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listLib.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listLib.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listLibValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listLib);

        loadLib.setText("Load");
        loadLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadLibActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(loadLib)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(loadLib)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listLibValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listLibValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listLibValueChanged

    private void loadLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadLibActionPerformed
        // TODO add your handling code here:
        String name = listLib.getSelectedValue().toString();
        name = name.substring(0, name.indexOf("."));
        Library libLoaded = listLibs.get(Integer.parseInt(name));
        System.out.println("load lib: " + libLoaded.id);
        libLoaded.loadLibrary(libLoaded.id);
        view.view2 view22 = view2.getIns();
        view.view1 view11 = view1.getIns();
        controller con = new controller(view22, libLoaded);
        view22.setVisible(true);
        view11.setVisible(false);
    }//GEN-LAST:event_loadLibActionPerformed

    /**
     * @param args the command line arguments
     */
    public void addListLibs(){
        ArrayList<Library> libs = new ArrayList<>();
         try{
        URL url = new URL("http://159.89.202.84:8080/api/sets?user_id=4E4ivDlfzf1MSpL2h69E");
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("GET");
            connection.setDoOutput(true);
            BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            String m = "";
            String inputLine;
            while ((inputLine = in.readLine()) != null){
               m += inputLine + "\n";
            }
            System.out.println(m);
            JSONObject json = new JSONObject(m);
            System.out.println(json.getString("message"));
            JSONArray libss = json.getJSONArray("resources");
            for (int i = 0; i< json.getJSONArray("resources").length(); i++){
                String id = libss.getJSONObject(i).getString("Id");
                String name = libss.getJSONObject(i).getString("Name");
                Library tmp = new Library(id, name);
                libs.add(tmp);
                System.out.println(libss.getJSONObject(i).getString("Id"));
            }
            in.close();
        } catch (Exception e){
            e.printStackTrace();
        }
         
        int index = 0;
        DefaultListModel dlm = new DefaultListModel();
        for (Library lib : libs){
           listLibs.add(lib);
           dlm.addElement(index++ +". " + lib.name);
        } 
        listLib.setModel(dlm);
    }
    
    DefaultListModel dlm2 = new DefaultListModel();
    ArrayList<Library> listLibs = new ArrayList<>();
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listLib;
    private javax.swing.JButton loadLib;
    // End of variables declaration//GEN-END:variables
}
